Search travel
FashioNXT/NXTFolio pull request #41
Opened 2023-04-30 08:01 UTC by wenyuanli0326

1. Log in as Anthony Gray.
2. Edit the travel information and enter a city, for example, Seattle. Set the start date to be within the next 30 days.
3. Navigate to the search page, enter the city in the search field, and click on the search button.
4. Verify that Anthony Gray appears in the search results.
5. Attempt to set the start date to be outside of the next 30 days.
6. Perform another search and verify that Anthony Gray no longer appears in the search results.

I also fix the country/state selection problem and set the city to be an input box. 

For tests:
run cucumber features/search_travel.feature 

Tests results:
<img width="1030" alt="search_travel_test" src="https://user-images.githubusercontent.com/98793421/235342424-98a86d61-7660-4849-b32a-78367d0abaf8.png">

2023-04-30 14:42 UTC, AJ1904 commented on app/models/general_info.rb
> +    puts "check adfsaf"
required?

2023-04-30 14:42 UTC, AJ1904 commented on app/models/general_info.rb
> +    puts city.present?
required?

2023-04-30 14:42 UTC, AJ1904 commented on app/models/general_info.rb
> +    puts city
required?

2023-04-30 14:49 UTC, AJ1904 requested changes
1. Update the travel statement according to what client asked for.
In city,state from 3-letter-month day to 3-letter-month day : [description]
2. Put validation - start date cannot be more than end date
3. Put validation -  current - 30 days <= start date <= current + 30 days
4. Travel info should be removed from database once current > end date

2023-04-30 14:51 UTC, AJ1904 requested changes
The app links (fb,linkedin,etc) should not go out of the box. They are inside the box in heroku, please fix in this branch.
<img width="583" alt="image" src="https://user-images.githubusercontent.com/49027490/235359662-824b84f6-f389-41f8-bd2a-2179dbad4192.png">

2023-05-01 01:39 UTC, wenyuanli0326 commented
Please check the commit history. Everything you mentioned are fixed.

2023-05-01 04:29 UTC, AJ1904 commented
Test case fails (because of the recent changes to general_steps.rb). Please update test case accordingly.
<img width="751" alt="image" src="https://user-images.githubusercontent.com/49027490/235406732-ff54d81f-bd2f-4616-a5a9-7e676ab5aa0e.png">

2023-05-01 20:58 UTC, baichuan0113 approved these changes

2023-05-02 02:54 UTC, AJ1904 approved these changes

2023-05-02 03:04 UTC, wenyuanli0326 commented
Modified test due to changes in general_steps. 

Test pass:
<img width="1242" alt="search_travel_test1" src="https://user-images.githubusercontent.com/98793421/235571084-d5269c75-8a47-4157-8512-2398dca665cb.png">

2023-05-02 03:05 UTC, merged